
server:
  port: 8761

eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
  client:
    register-with-eureka: false
    fetch-registry: false
  service-url:
    defaultZone: http://130.194.72.3:8761/eureka/

logging:
  config: classpath:logback.xml