mybatis-plus:
  mapper-locations: classpath*:com/monash/analyticcs/**/xml/*Mapper.xml
  global-config:
    id-type: 0
    db-column-underline: false
    refresh-mapper: true

spring:
  application:
    name: position-service
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/for_future_use?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false&serverTimezone=UTC
    username: root
    password: 5r6t7y8U
    filters: log4j,wall,mergeStat

server:
  port: 7201

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/


logging:
  config: classpath:logback.xml

